### ISSUE TITLE
Related Terms

### ISSUE THREAD

**Issue by ThariqS** [ThariqS/NewsCloudsGenerator#1]
On the master branch I've added related terms at this URL: 

`http://localhost:8080/relatedTerms?title=obama` 

In tilteOperator.js you want to extract the related span: `<strong>Related:</strong> Campaign, Cruz, Rubio, Mexico</span></span>` and move it into its own component, it'll work a lot like graph.js in that it should take in a title and render things.

**Comment by amruss** [comment]
![screen shot 2016-03-02 at 9 08 20 pm](https://cloud.githubusercontent.com/assets/13264141/13482441/4814e616-e0bb-11e5-8397-3bb4e5a42f94.png)
